### ISSUE TITLE
Accessibility - Add label to search input

### ISSUE THREAD

**Issue by halocline** [hpe-design/design-system#240] opened 2020-01-17 15:38 UTC
![Screen Shot 2020-01-17 at 8 37 01 AM](https://user-images.githubusercontent.com/1756948/72624795-ca01f600-3904-11ea-9d31-4d609dafba02.png)

**Comment by taysea** [comment] 2020-01-17 15:41
This is a duplicate of #201 , I will leave this one open and close that one.

**Closed** 2020-01-27 16:31 UTC
Labels: accessibility
