### ISSUE TITLE
Text and icon alignment in other browsers can be off

### ISSUE THREAD

**Issue by gregfuruiye** [hpe-design/design-system#1006] opened 2020-07-31 20:09 UTC
This may actually need to occur in the Designer repo, but maybe it occurs with the theme? Anyhow, here are a couple screenshots from Edgar's windows machine:

![image (6)](https://user-images.githubusercontent.com/17889451/89073854-861e8d80-d338-11ea-8f7c-6bb304c92a4b.png)
![image (7)](https://user-images.githubusercontent.com/17889451/89073865-8a4aab00-d338-11ea-9ba0-798293a0dc54.png)

**Comment by halocline** [comment] 2020-08-04 15:15
**Background**: 
I believe this issue is still related to when we introduced MetricHPEXS fonts. The font files included a baseline [I think] adjustment which shifts the vertical alignment of the font. This is resulting in the font being shifted upward in relation to the rest of the container.

The font placement seems to be related to browser + OS, specifically it is most exaggerated when using Firefox/Windows.

If I recall, the original motivation to update the font files were to:
- Smooth out some of the curve renderings on some characters. The solution for this was to serve the fonts using the .woff2 file format which has better compression and is supposed to maintain the character integrity. 
- I think the adjusted baseline was an opportune refinement.

Tasks:
- [ ] Reproduce the issue on Browserstack
- [ ] Test whether the issue occurs when using MetricHPE vs. MetricHPEXS
- [ ] Determine move forward approach:
  - Fix short-term:
    - Revert to MetricHPE
    - Revert to MetricHPE + provide MetricHPE in .woff and .woff2 formats
  - Fix long-term:
    - Fix MetricHPEXS

**Comment by halocline** [comment] 2020-08-07 22:17
- [ ] Fix has been applied
- [ ] Files uploaded to CDN AWS-S3 
- [ ] Document process, settings, resources for those to come in the future
- [ ] Fine tuning session w/ a designer (right now we are accommodating for fitting all glyphs, and may want to make fine tuning adjustments for purely aesthetical reasons)

**Comment by halocline** [comment] 2020-08-11 14:25
Steps taken to fix alignment:

- The source of the alignment issue was related to the actual font files. Specifically, the "vertical metrics" which are configurable.
- To adjust the Vertical Metrics:
  - Get .otf or equivalent source file
  - Open with font editor (I used the program Glyphs)
  - Open the "Show Font Info" window from UI menu or file menu (command + I)
![Screen Shot 2020-08-11 at 8 12 55 AM](https://user-images.githubusercontent.com/1756948/89908555-4020bf80-dbab-11ea-876f-0a1acabae834.png)
  - Adjust the settings for the various ascenders, descenders, and gap - [Detailed Reference](https://glyphsapp.com/tutorials/vertical-metrics):
    - winAscent
    - winDescent
    - typoAscender
    - typoDescender (negative value)
    - typoLineGap
    - hheaAscender
    - hheaDescender (negative value)
    - hheaLineGap
![Screen Shot 2020-08-11 at 8 13 21 AM](https://user-images.githubusercontent.com/1756948/89908580-46af3700-dbab-11ea-8ed6-132bedb5f522.png)
- Save Glyphs font file --> File Save / Save As
- Export --> File Export OTF version --> repeat for Webfont versions (.woff and .woff2)
- Upload to AWS S3 Bucket (https://s3.console.aws.amazon.com/s3/buckets/hpe-design-system/?region=us-east-1&tab=overview) and make sure the "Make Public" option is enabled for all font files, otherwise the file request will return a 403 server response.
- Repeat for all font weights, both regular and italic

**Closed** 2020-08-13 17:42 UTC
